---

- hosts: to_deploy_ubuntu_servers
  become: true
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:

    - name: update repo 1st
      apt:
        update_cache: yes

    - name: upgrade packages
      apt:
        upgrade: yes
  
    - name: Append custom prompt and aliases to .bashrc
      ansible.builtin.blockinfile:
        path: "/home/coffee/.bashrc"
        block: "{{ lookup('ansible.builtin.file', '/home/coffee/ansible1/configs/bashrc_server.sh') }}"
        state: present

    - name: Customize sudoers file
      ansible.builtin.blockinfile:
        path: "/etc/sudoers"
        block: "{{ lookup('ansible.builtin.file', '/home/coffee/ansible1/configs/sudoers_nopass.sh') }}"
        state: present

    - name: Install additional packages for Ubuntu servers
      apt:
        pkg:
          - htop
          - btop
          - qemu-guest-agent
          - net-tools
          - ncdu
          - cifs-utils
          - nfs-common
          - nala
          - python-is-python3
        state: latest
        update_cache: true
 
    - name: Install required Docker packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - docker-compose

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: coffee
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

    - name: clean old packages
      apt:
        autoremove: true
    
    - name: final system reboot
      ansible.builtin.reboot:

