---

- hosts: all
  become: true
  
  tasks:
    - name: update repo 1st
      apt:
        update_cache: yes

    - name: install apache2 package and php support for apache2
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest