---

- hosts: local_ubuntu_servers
  become: true
  
  tasks:
    - name: update repo 1st
      apt:
        update_cache: yes

    - name: upgrade packages
      apt:
        upgrade: yes

    - name: clean old packages
      apt:
        autoremove: true

    - name: reboot system after upgrade
      ansible.builtin.reboot: